# Generated by Django 4.1.7 on 2023-06-08 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(related_name='followed_by', through='users.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
