# Generated by Django 4.1.7 on 2023-03-29 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mems', '0002_alter_comment_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='mems',
            field=models.ManyToManyField(blank=True, related_name='group_mems', to='mems.mem'),
        ),
    ]
