# Generated by Django 4.1.7 on 2023-03-20 11:05

import apps.mems.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mems', '0003_alter_mem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(1), related_name='mems', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
