# Generated by Django 4.1.7 on 2023-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0003_alter_group_members_alter_group_mems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mems',
        ),
        migrations.AddField(
            model_name='mem',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='mems_group', to='mems.group'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mems', to='mems.tag'),
        ),
    ]
