# Generated by Django 4.1.7 on 2023-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0004_remove_group_mems_mem_groups_alter_mem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='vote_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
