# Generated by Django 4.1.7 on 2023-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0008_comment_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=70),
        ),
    ]
