# Generated by Django 4.1.7 on 2023-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0009_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='mems', to='mems.tag'),
        ),
    ]
