# Generated by Django 4.1.7 on 2023-06-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0010_alter_mem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mems', to='mems.tag'),
        ),
    ]
